import "../styles/global.css";
import { Inter } from "next/font/google";
import Nav from "../components/Nav";
import Footer from "../components/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main className="app">
          <Nav />
          {children}
          <Footer />
        </main>
        <script
          src="https://kit.fontawesome.com/a31bdd6d95.js"
          crossorigin="anonymous"
        ></script>
      </body>
    </html>
  );
}
